topSpeed = 100

def on_forever():
    pins.servo_write_pin(AnalogPin.P14, 90)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, topSpeed)
    basic.pause(2000)
    pins.servo_write_pin(AnalogPin.P14, 60)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(3000)
    pins.servo_write_pin(AnalogPin.P14, 90)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(2000)
    pins.servo_write_pin(AnalogPin.P14, 120)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(3000)
    pins.servo_write_pin(AnalogPin.P14, 90)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(1000)
    pins.servo_write_pin(AnalogPin.P14, 60)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(2000)
    pins.servo_write_pin(AnalogPin.P14, 90)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(1000)
    pins.servo_write_pin(AnalogPin.P14, 120)
    ContinuousServo.spin_one_way_with_speed(AnalogPin.P13, 50)
    basic.pause(2000)
basic.forever(on_forever)
